### ISSUE TITLE
Problem on compile with Raspberry pi2 and GCC 14.2.0

### ISSUE THREAD

**Issue by Sicand** [abhiTronix/raspberry-pi-cross-compilers#124]
Hi , when i launch the makefile of a program i get this 
With gcc 14.2.0 make stop at this
from crypto/tsBlockCipher.h:15,
from crypto/tsAES128.h:15,
from crypto/tsAES128.cpp:9:
/opt/gcc-14.2.0/include/c++/14.2.0/bits/semaphore_base.h:59:41: error: '_POSIX_SEM_VALUE_MAX' was not declared in this scope; did you mean '_SC_SEM_VALUE_MAX'?
59 | static constexpr ptrdiff_t _S_max = _POSIX_SEM_VALUE_MAX;
| ^~~~~~~~~~~~~~~~~~~~
| _SC_SEM_VALUE_MAX

No problem with clang compiler

Whats Can i do ?
